experiment:
  name: "/Shared/penrose"
  tracking_uri: "sqlite:///mlruns.db"
  artifact_location: "./mlruns"

model_registry:
  # Specifies the name of the Registered Model to use when registering a trained model to
  # the MLflow Model Registry
  model_name: {{MODEL_NAME|default('penrose_model')}}

# Override the default train / validation / test dataset split ratios
SPLIT_RATIOS: [0.80, 0.10, 0.10]

INGEST_CONFIG:
  # For different options please read: https://github.com/mlflow/recipes-regression-template#ingest-step
  using: parquet
  location: "./data/sample.parquet"
  loader_method: load_file_as_dataframe

INGEST_SCORING_CONFIG:
  # For different options please read: https://github.com/mlflow/recipes-regression-template#batch-scoring
  using: parquet
  location: "./data/sample.parquet"
  loader_method: load_file_as_dataframe

PREDICT_OUTPUT_CONFIG:
  # For different options please read: https://github.com/mlflow/recipes-regression-template#predict-step
  using: parquet
  location: "./data/sample_output.parquet"
